name       : nvme-cli
version    : 1.2
release    : 1
source     :
    - https://github.com/linux-nvme/nvme-cli/archive/v1.2.tar.gz : f7ecd8138caba3a6d3a95d871a1ffcef64d77a015d3611e5cf962787bc354221
license    : GPL-2.0
component  : system.utils
summary    : NVM-Express user space tooling for Linux.
description: |
    NVM-Express user space tooling for Linux.
build      : |
    %make
install    : |
    PREFIX=/usr %make_install