name       : nvme-cli
version    : 2.1.1
release    : 12
source     :
    - https://github.com/linux-nvme/nvme-cli/archive/refs/tags/v2.1.1.tar.gz : cc8bd36b9aa71243e2bace238aa5505244fef3fef5418b0c61f75d1988458272
license    : GPL-2.0-only
component  : system.utils
summary    : NVM-Express user space tooling for Linux.
description: |
    NVM-Express user space tooling for Linux.
builddeps  :
    - pkgconfig(libnvme)
setup      : |
    %meson_configure \
        -Dudevrulesdir=lib64/udev/rules.d \
        -Dsystemddir=lib/systemd/system \
        -Ddocs=man
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Remove default/example config
    rm -rv $installdir/etc/
