name       : nvme-cli
version    : '1.7'
release    : 3
source     :
    - https://github.com/linux-nvme/nvme-cli/archive/v1.7.tar.gz : 3a139d40ffff48d2f0b06339fd3be3ed219241ce6838f0ea173d7459c9984ea2
license    : GPL-2.0-only
component  : system.utils
summary    : NVM-Express user space tooling for Linux.
description: |
    NVM-Express user space tooling for Linux.
build      : |
    CFLAGS="${CFLAGS} -I." %make
install    : |
    PREFIX=/usr %make_install
