name       : nvme-cli
version    : 1.3
release    : 2
source     :
    - https://github.com/linux-nvme/nvme-cli/archive/v1.3.tar.gz : 52eb45c9ef5a529580a3f6f9e02c067695675ac01b8ab8b8e0398c62e8a8646d
license    : GPL-2.0
component  : system.utils
summary    : NVM-Express user space tooling for Linux.
description: |
    NVM-Express user space tooling for Linux.
build      : |
    %make
install    : |
    PREFIX=/usr %make_install
