name       : nvme-cli
version    : '1.13'
release    : 6
source     :
    - https://github.com/linux-nvme/nvme-cli/archive/v1.13.tar.gz : 03f4875f3e68d326b0280e16df2f027ca6b086cfa148c34e8569df61319b4b85
license    : GPL-2.0-only
component  : system.utils
summary    : NVM-Express user space tooling for Linux.
description: |
    NVM-Express user space tooling for Linux.
environment: |
    export CFLAGS="${CFLAGS} -I."
    export PREFIX=/usr
    export UDEVDIR=/usr/lib64/udev
build      : |
    %make
install    : |
    %make_install

    # Remove default/example config
    rm -r $installdir/etc/
