name       : nvme-cli
version    : 1.12.0
release    : 5
source     :
    - https://github.com/linux-nvme/nvme-cli/archive/v1.12.tar.gz : a75270e65a4a7a6add48f748ba216d8f68d78f90f8cb77e88e9753b74d527991
license    : GPL-2.0-only
component  : system.utils
summary    : NVM-Express user space tooling for Linux.
description: |
    NVM-Express user space tooling for Linux.
environment: |
    export CFLAGS="${CFLAGS} -I."
    export PREFIX=/usr
    export UDEVDIR=/usr/lib64/udev
build      : |
    %make
install    : |
    %make_install

    # Remove default/example config
    rm -r $installdir/etc/
