name       : nvme-cli
version    : 1.8.1
release    : 4
source     :
    - https://github.com/linux-nvme/nvme-cli/archive/v1.8.1.tar.gz : 93b9134b7a4cc36c9444b9ee52ef016be6e3e2f2ece50fab1f4a56ebe1e3612b
license    : GPL-2.0-only
component  : system.utils
summary    : NVM-Express user space tooling for Linux.
description: |
    NVM-Express user space tooling for Linux.
build      : |
    CFLAGS="${CFLAGS} -I." %make
install    : |
    PREFIX=/usr %make_install
